# -*- coding: utf-8 -*-
"""capstone project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qHTsLfkB336NSeZcCaPpF7BikyzhuEu
"""

import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer

def generate_song_lyrics(prompt, max_length=200):
    # Load the pre-trained model and tokenizer
    tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
    model = GPT2LMHeadModel.from_pretrained('gpt2')

    # Encode the input prompt to get the tokenized version
    encoded_prompt = tokenizer.encode(prompt, add_special_tokens=False, return_tensors='pt')

    # Generate a sequence of tokens following the prompt
    output_sequences = model.generate(
        input_ids=encoded_prompt,
        max_length=max_length + len(encoded_prompt[0]),
        temperature=0.8,
        top_p=0.9,
        do_sample=True,
        num_return_sequences=1
    )

    # Decode the output tokens to get the generated text
    generated_sequence = output_sequences[0].tolist()
    text = tokenizer.decode(generated_sequence, clean_up_tokenization_spaces=True)

    # Remove the input prompt from the generated text and return the result
    return text[len(tokenizer.decode(encoded_prompt[0], clean_up_tokenization_spaces=True)):]

# Example usage
prompt = "In the game where the stakes are life or death,"
print(generate_song_lyrics(prompt))

def print_song_lyrics():
    title = "Streets Never Sleep"
    hook = """In the game where the stakes are life or death,
Streets never sleep, always watch your step.
Trust is costly, betrayal comes cheap,
In the shadows, secrets we keep."""

    verse1 = """Hustle hard in the silence of the concrete jungle,
Every corner turned, another chance to tumble.
Eyes wide, mind sharper than a blade,
Living by the code that the streets have made.

Money on the mind, power in the grip,
Every word loaded like a clip.
Respect isn't given, it's earned with fear,
Rise to the top, make the rivals disappear."""

    verse2 = """Gold chains, cold nights, the hustle never ends,
Loyalty is rare, fewer friends.
The throne is lonely when you sit at the peak,
Enemies close, the vengeance they seek.

Running the streets with an iron fist,
In a world where only the ruthless exist.
Playing for keeps, in the fast lane dive,
Only the strongest will survive."""

    bridge = """Cruising down the boulevard, under neon lights,
Living in a war zone, fighting for our rights.
Money, power, respect, the eternal chase,
In the heart of the city, every day’s a race."""

    # Print each part of the song
    print(title.upper() + "\n")
    print("Hook:\n" + hook + "\n")
    print("Verse 1:\n" + verse1 + "\n")
    print("Hook:\n" + hook + "\n")
    print("Verse 2:\n" + verse2 + "\n")
    print("Bridge:\n" + bridge + "\n")
    print("Hook:\n" + hook + "\n")

# Call the function to print the song lyrics
print_song_lyrics()

pip install streamlit

import streamlit as st

def main():
    st.title("Streets Never Sleep")

    hook = """In the game where the stakes are life or death,
Streets never sleep, always watch your step.
Trust is costly, betrayal comes cheap,
In the shadows, secrets we keep."""

    verse1 = """Hustle hard in the silence of the concrete jungle,
Every corner turned, another chance to tumble.
Eyes wide, mind sharper than a blade,
Living by the code that the streets have made.
Money on the mind, power in the grip,
Every word loaded like a clip.
Respect isn't given, it's earned with fear,
Rise to the top, make the rivals disappear."""

    verse2 = """Gold chains, cold nights, the hustle never ends,
Loyalty is rare, fewer friends.
The throne is lonely when you sit at the peak,
Enemies close, the vengeance they seek.
Running the streets with an iron fist,
In a world where only the ruthless exist.
Playing for keeps, in the fast lane dive,
Only the strongest will survive."""

    bridge = """Cruising down the boulevard, under neon lights,
Living in a war zone, fighting for our rights.
Money, power, respect, the eternal chase,
In the heart of the city, every day’s a race."""

    st.header("Hook")
    st.write(hook)
    st.header("Verse 1")
    st.write(verse1)
    st.header("Hook (Repeat)")
    st.write(hook)
    st.header("Verse 2")
    st.write(verse2)
    st.header("Bridge")
    st.write(bridge)
    st.header("Hook (Final)")
    st.write(hook)

if __name__ == "__main__":
    main()